### ISSUE TITLE
API: Usage & how to use

### ISSUE THREAD

**Issue by sillyjohn** [sillyjohn/CS401_Project2#13]

**Comment by sillyjohn** [comment]
This is a link on how those json file can be used:
https://developer.riotgames.com/docs/lol
Additionally, there are links for the png files for all champions and items such as: https://ddragon.leagueoflegends.com/cdn/14.5.1/data/en_US/champion.json

**Comment by Tedla610** [comment]
API references:
https://developer.riotgames.com/apis#account-v1

**Comment by sillyjohn** [comment]
https://www.tutorialspoint.com/how-to-send-post-requests-in-json-using-http-client-in-android

**Comment by sillyjohn** [comment]
https://www.geeksforgeeks.org/how-to-make-an-http-request-with-android/

**Comment by sillyjohn** [comment]
API request done inside championViewModel
